2016-06-10 09:21:42,088 [6] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-10 09:21:52,397 [8] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-10 09:21:59,719 [8] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-10 10:28:45,174 [9] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-10 10:35:13,414 [6] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
2016-06-10 14:36:31,633 [8] ERROR WOW.SaveTool.Data.CustomerRepository - System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
WOW.Care.Contracts.CustomExceptions.CustomException: Exception of type 'WOW.Care.Contracts.CustomExceptions.CustomException' was thrown.
   at WOW.Care.Core.Customer.CustomerSearchAllBilingSystems.CustomerDetails(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at WOW.Care.Services.Customer.<>c__DisplayClassd.<CustomerDetailsByAccountNumber>b__c()
   at WOW.Care.Core.BaseClasses.ServiceBase.ExecuteFaultHandledOperation[T](Func`1 codetoExecute, IUserDbRequest userDbRequests, IValidator validator, Object request)
   at WOW.Care.Services.Customer.CustomerDetailsByAccountNumber(CustomerDetailsByAccountNumberRequest customerDetailsRequest)
   at Castle.Proxies.Invocations.ICustomer_CustomerDetailsByAccountNumber.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at WOW.Care.Common.Logging.LoggingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.Abs...).
